### ISSUE TITLE
Total and circulating supply endpoints for integration with CMC

### ISSUE THREAD

**Issue by aesedepece** [drcpu-github/witnet-explorer-backend#1]
CMC currently supports automated updates of the total and circulating supplies by reading from some API endpoint that provides that data.

This is an example:

- https://btc.cryptoid.info/btc/api.dws?q=totalcoins
- https://btc.cryptoid.info/btc/api.dws?q=circulating

The URL of the endpoints can be free-form, but the response needs to be in plain format (no JSON fanciness), just as the examples above.

We need to take into account that as per CMC methodology, total supply for Witnet means `circulating + locked`.

**Comment by drcpu-github** [comment]
Closed with merging of PR #2.
